export const sampleTripPlan = {
  id: "sample-trip-plan",
  title: "Three Days In Kyoto",
  destination: "Kyoto",
  summary: "A balanced first-time Kyoto itinerary with temples, market food, gardens, and low-friction evenings.",
  travelStyle: "Culture and food",
  createdAt: new Date().toISOString(),
  days: [
    {
      id: "day-1",
      dateLabel: "Day 1",
      title: "Arrival And Downtown Wandering",
      theme: "Ease in with food streets and a gentle evening walk.",
      notes: "Keep the first day flexible in case trains or check-in take longer than expected.",
      stops: [
        {
          id: "day-1-stop-1",
          time: "2:00 PM",
          title: "Check In Near Shijo",
          location: "Shijo-Karasuma",
          duration: "45 min",
          category: "Logistics",
          description: "Drop bags, refresh, and get oriented around the nearest subway and bus stops.",
          tips: ["Buy or top up an IC card before heading out."],
          cost: "",
          bookingNeeded: false,
        },
        {
          id: "day-1-stop-2",
          time: "4:00 PM",
          title: "Nishiki Market",
          location: "Downtown Kyoto",
          duration: "90 min",
          category: "Food",
          description: "Try small bites like tamagoyaki, skewers, pickles, and matcha sweets.",
          tips: ["Bring cash for smaller vendors.", "Eat while standing near each stall."],
          cost: "$",
          bookingNeeded: false,
        },
        {
          id: "day-1-stop-3",
          time: "6:30 PM",
          title: "Pontocho Alley",
          location: "Kamo River",
          duration: "2 hr",
          category: "Dinner",
          description: "Walk the lantern-lit alley and pick a relaxed izakaya or noodle shop for dinner.",
          tips: ["Peak dinner windows fill quickly."],
          cost: "$$",
          bookingNeeded: false,
        },
      ],
    },
    {
      id: "day-2",
      dateLabel: "Day 2",
      title: "Shrines, Temples, And Old Lanes",
      theme: "Classic sights with quieter timing.",
      notes: "Start early to avoid the busiest shrine paths.",
      stops: [
        {
          id: "day-2-stop-1",
          time: "7:30 AM",
          title: "Fushimi Inari Taisha",
          location: "Fushimi",
          duration: "2 hr",
          category: "Shrine",
          description: "Walk through the torii gates and turn back around the Yotsutsuji viewpoint if time is tight.",
          tips: ["Wear shoes with grip.", "The lower gates are busiest by mid-morning."],
          cost: "Free",
          bookingNeeded: false,
        },
        {
          id: "day-2-stop-2",
          time: "11:30 AM",
          title: "Kiyomizu-Dera",
          location: "Higashiyama",
          duration: "90 min",
          category: "Temple",
          description: "Visit the temple balcony, then follow the preserved shopping lanes downhill.",
          tips: ["Taxi or bus saves time between Fushimi and Higashiyama."],
          cost: "$",
          bookingNeeded: false,
        },
        {
          id: "day-2-stop-3",
          time: "3:00 PM",
          title: "Gion And Hanamikoji",
          location: "Gion",
          duration: "90 min",
          category: "Walk",
          description: "Explore historic lanes, tea houses, and small side streets without rushing.",
          tips: ["Be respectful around private lanes and photography signs."],
          cost: "Free",
          bookingNeeded: false,
        },
      ],
    },
    {
      id: "day-3",
      dateLabel: "Day 3",
      title: "Arashiyama And Gardens",
      theme: "A scenic western Kyoto day.",
      notes: "The bamboo grove is calmest early, then the day can slow down around gardens and riverside cafes.",
      stops: [
        {
          id: "day-3-stop-1",
          time: "8:00 AM",
          title: "Arashiyama Bamboo Grove",
          location: "Arashiyama",
          duration: "45 min",
          category: "Nature",
          description: "Walk the grove before tour groups arrive, then continue toward nearby temple gardens.",
          tips: ["Arrive before 9 AM for the quietest path."],
          cost: "Free",
          bookingNeeded: false,
        },
        {
          id: "day-3-stop-2",
          time: "9:00 AM",
          title: "Tenryu-Ji",
          location: "Arashiyama",
          duration: "75 min",
          category: "Garden",
          description: "Visit the Zen garden and pond, one of the most rewarding garden stops in the area.",
          tips: ["Enter through the north gate after the bamboo grove."],
          cost: "$",
          bookingNeeded: false,
        },
        {
          id: "day-3-stop-3",
          time: "12:30 PM",
          title: "Katsura River Lunch",
          location: "Togetsukyo Bridge",
          duration: "90 min",
          category: "Lunch",
          description: "Choose soba, tofu, or a riverside cafe before heading back into central Kyoto.",
          tips: ["Keep one backup restaurant nearby."],
          cost: "$$",
          bookingNeeded: false,
        },
      ],
    },
  ],
};
